### ISSUE TITLE
Regression Testing - Verifying the output of the script function ( Local login banner )

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#10]
There is a problem when the same input is given twice. Since the banner is configured in the first instance, after giving that input in the second instance, it should give an output like "The local login warning banner has already been configured!"

- First Input : 1
Output : "Local Login Warning Banner change SUCCESS: banner changed!"

- Second input : 1
Expected output :"The local login warning banner has already been configured!"
Output : "Local Login Warning Banner change FAILED: error file seems to be changed"
![twice](https://github.com/rajin4463/Centinal/assets/107628399/f1fe6b20-9624-4dee-bddc-e118eb8f23d4)

**Comment by rajin4463** [comment]
The issue has been fixed check has been added to see if the banner exists in the file.
