### ISSUE TITLE
Negative Test Cases - Unexpected inputs (Special characters)

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#17]
The following problem was encountered while testing the relevant code under unexpected input handling conditions in the script:
Test case - Validate error handling for an invalid inputs(Special characters : !@#$%^&*()_+[{]}|;:'",<.>/? )

input : "%"
Expected output : "Invalid input! Try again"
Output :
![new](https://github.com/rajin4463/Centinal/assets/107628399/81d20740-d1cb-4f8f-b7b6-ab034d1aed4b)

**Comment by rajin4463** [comment]
error was fixed in issue number #4 however in dev testing code has been updated to display error. fix will be push.
