### ISSUE TITLE
Understand the Requirements  - The telnet client is not disabled.

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#19]
**Understand the Requirements  - The telnet client is not disabled.**
Input : 2
Expected Outcome : Successfully purged Telnet Client
Output : 
![telnet](https://github.com/rajin4463/Centinal/assets/107628399/30fdffb9-a76c-4231-91a7-0c70ebec842a)

logging.txt output:
![error](https://github.com/rajin4463/Centinal/assets/107628399/6954ef81-24a8-4994-9f6f-e32423ee9536)

**Comment by rajin4463** [comment]
Error is caused by another process (process `2420` as indicated by the logs) using the command `dpkg`
