### ISSUE TITLE
Password Creation Requirements control not running when simultaneous control execution is enabled.

### ISSUE THREAD

**Issue by NaviduPerera** [rajin4463/Centinal#23]
When attempting to configure all settings simultaneously, the password creation requirements do not function as intended.
![Error screenshot](https://github.com/rajin4463/Centinal/assets/107617530/4b67434c-d61e-4c37-a0a3-22844ce71cde)

**Comment by rajin4463** [comment]
Please provide more information and screenshots of the problem.

**Comment by rajin4463** [comment]
Wont fix due to changes requested by the stakeholder as mentioned on git issue #24
