### ISSUE TITLE
OS testing

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#28]
The python script should only run on the Ubuntu 22.04 LTS. But this also runs on kali linux system.
![os](https://github.com/rajin4463/Centinal/assets/107628399/e728c062-ed79-467b-9bb3-5d65887f4077)

**Comment by rajin4463** [comment]
Issue fixed on commit 03d07e2895cb1c1dcf7b5b4ba2959e6fbf7398be 
os check has been switched from `lsb_release -ds` command to `/etc/os-release` file
Pull request has been made request ob #29
