### ISSUE TITLE
Update Error messages to be more clear in context.

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#30]
Modify the error messages.
![banner](https://github.com/rajin4463/Centinal/assets/107628399/155eaf1b-f54e-4b51-94c1-0434146141d0)
![telnetp](https://github.com/rajin4463/Centinal/assets/107628399/e1626bf7-c273-4bbf-9095-3b111212caa0)
![re](https://github.com/rajin4463/Centinal/assets/107628399/39be9b16-98f6-424b-bce6-f299b1dc9252)

**Comment by rajin4463** [comment]
Minimum password change unknown username error crash fixed in commit 275459176050f7d8458002d7f4c715ba7526d3b1

**Comment by rajin4463** [comment]
Local Login Warning banner re-change error updated for better context in commit  97f4b5fb82420ed0b82758594e0672fda34a7738

**Comment by rajin4463** [comment]
Fixed 97f4b5fb82420ed0b82758594e0672fda34a7738
