### ISSUE TITLE
Negative Test Cases - Unexpected inputs (Special characters)

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#4]
The following problem was encountered while testing the relevant code under unexpected input handling conditions in the script:
Test case - Validate error handling for an invalid inputs(Special characters : !@#$%^&*()_+[{]}\|;:'",<.>/? )

input : "!"
Expected output : "Invalid input! Try again"
Output :
![Unexpected_inputs_specail_characters_2](https://github.com/rajin4463/Centinal/assets/107628399/bddf75e0-11ca-44aa-a96e-ae0d4a7c2fa4)
![Unexpected_inputs_specail_characters_1](https://github.com/rajin4463/Centinal/assets/107628399/8040f7c8-1c76-430d-9fe4-a6e7568e8295)
![Unexpected_inputs_specail_characters_3](https://github.com/rajin4463/Centinal/assets/107628399/0a1695df-9fc5-4a07-8242-b823d71ec4ae)

**Comment by rajin4463** [comment]
Issue is the same as issue #3. Issue has been fixed.
