### ISSUE TITLE
Track and Report Defects- Verifying the output of the script function

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#6]
It appears that there is an error in the output of the script function.

**Track and Report Defects- Verifying the output of the script function**
input : 1
Expected output : Local Login Warning Banner change SUCCESS: banner changed!
Output : Local Login Warning Banner change FAILED: error file seems to be changed
![login](https://github.com/rajin4463/Centinal/assets/107628399/64e75700-f433-4ed2-a89e-51988e017def)

**Comment by rajin4463** [comment]
The issue is caused by the comparison of the output of `/etc/issue`  being too specific and outdated.

Issue fixed in commit 61d51bb0a8d5d91fe42e7d87d3efad41d55aeda5
