### ISSUE TITLE
Understand the Requirements - The local login banner is not displayed

### ISSUE THREAD

**Issue by janithDakshitha** [rajin4463/Centinal#8]
After configuring the "Ensure local login warning banner is properly configured (1.7.2)" benchmark, the script should display the local login banner to the user when  logging to a new terminal. But it seems that the related function is missing in the script.

**Understand the Requirements - The local login banner display function is missing**
Input : 1
Expected Outcome no-1 : Local Login Warning Banner change SUCCESS: banner changed!
Expected Outcome no-2 : WARNING: Unauthorized access to this system is prohibited. By accessing this system, you agree that your actions may be monitored and recorded.

Expected Outcome no-1 : Fine
![local](https://github.com/rajin4463/Centinal/assets/107628399/45a76cfe-c4bf-4945-be26-69112821127c)

Expected Outcome no-2 : The banner is not displayed when the user logs into the system.
![local2](https://github.com/rajin4463/Centinal/assets/107628399/2f5a9878-be54-48f2-abda-0b7b743d0f38)

**Comment by rajin4463** [comment]
The solution requires the modification of the `~/.bashrc` for the banner to appear on login.

**Comment by rajin4463** [comment]
The issue has been fixed in the commit c081b45970cbc707197adf056852b143715f0d44
